name: FirecraftCore
main: net.firecraftmc.core.FirecraftCore
version: 1.7.1-ALPHA
load: STARTUP
author: Firestar311
commands:
    chat:
        description: Base command for everything chat.
        aliases: [c]
    gamemode:
        aliases: [gm]
    gmc:
    gms:
    gmsp:
    gma:
    teleport:
        aliases: [tp]
    nick:
    vanish:
        aliases: [v]
    nickconfirm:
    nickcancel:
    unnick:
        aliases: [resetnick, nickreset]
    nickrandom:
    back:
    tphere:
    tpall:
    tpa:
       aliases: [tpr]
    tpaccept:
    tpdeny:
    setspawn:
    spawn:
    dev:
    signedit:
    ban:
    tempban:
    mute:
    tempmute:
    jail:
    kick:
    warn:
    setjail:
    ipban:
    setlore:
    setname:
    unban:
    unmute:
    unjail:
    players:
    fct:
        aliases: [firecraftteam]
    weather:
    time:
    day:
    night:
    broadcast:
        aliases: [bc]
    socketbroadcast:
        aliases: [sbc]
    clearinventory:
        aliases: [ci]
    enderchest:
        aliases: [echest, ec]
    workbench:
        aliases: [craft, wb]
    invsee:
    sethome:
        aliases: [sh]
    delhome:
        aliases: [dh]
    home:
        aliases: [h]
    setwarp:
    delwarp:
    warp:
    report:
    reportadmin:
        aliases: [ra]
    list: